# Generated by Django 3.0.8 on 2020-07-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tab',
            new_name='Db',
        ),
    ]
